# Site settings
title: "Christian Geier, MD | Academic Website"
description: "Research Interests include Dendritic Cell Interactions with T cells as a potential disease pathway driving Rheumatoid Arthritis."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Christian Geier"
resume_title:                   "Researching Rheumatoid Arthritis at Columbia University"

# used for the contact button in _layouts/resume.html
# resume_contact_email:           "lisasimpson@youremailaddress.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "212-305-4308"
resume_contact_address:         "650 W 168th St, New York, NY 10032"

resume_header_contact_info:     "New York, NY • 212-305-4308 • christian.geier _at_ posteo.net"
display_header_contact_info:    "true"

resume_header_intro: <b>Bio.</b> I'm a Rheumatology Fellow at Columbia University School of Medicine working in the lab of <a href="https://www.rheumatologyatcolumbia.org/research-labs/winchester-lab">Robert Winchester</a>. I am responsible for the acquisition, optimization and analysis of multicolor and spectral flow cytometry data to study the adaptive immune system. My research focuses on understanding of the potential pathologic functions of dendritic cells (DC) and their interactions with other immune cells in the context of autoimmune diseases such as Rheumatoid Arthritis and Lupus (SLE). <p>I am particularly interested in novel approaches to the analysis of complex data as it is generated in multicolor and spectral flow cytometry experiments, and methods to integrate that data with clinical information. Our goal is to detect the cellular mechanisms that are responsible for the development and maintenance of autoimmune diseases and to ultimately enable new targeted therapies that improve lives with people living with autoimmune diseases such as Rheumatoid arthritis and Lupus.


# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
# resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_research_experience:      true
resume_section_clinical_experience:      true
resume_section_education:       true
resume_section_honor:     true
resume_section_publications:        true
resume_section_skills:          true
resume_section_licensure:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "https://twitter.com/cgeierRA"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/christian-geier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_researchgate_url:      "https://www.researchgate.net/profile/Christian_Geier4"
  resume_website_url:           "https://christiangeier.co"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
